language: node_js
node_js:
  - "node"

install:
  - npm install
script:
  - npm run build


deploy:
  #deploy to libamtrack.github.io/web
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN # defined at Travis/Settings/Environment Variables
  keep-history: true
  local-dir: ./dist
  on:
    branch: master

  #deploy to libamtrack.github.io/web_dev
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN # defined at Travis/Settings/Environment Variables
  keep-history: true
  local-dir: ./dist
  repo: libamtrack/web_dev
  target-branch: master
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^feature #deploy when commit to branch feature
